# Site settings
title: Nerdorade
email: jake@nerdorade.com
description: > # this means to ignore newlines until "baseurl:"
  Nerdorade is a website designed to provide high level blog posts regarding programming, and more specifically web development. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nerdorade.com" # the base hostname & protocol for your site
twitter_username: realmunsterberg
github_username:  munsterberg

# Build settings
markdown: kramdown
