# Site settings
title: Oshawa Design
email: jake@oshawadesign.com
description: > # this means to ignore newlines until "baseurl:"
  Oshawa Design is a website designed to provide high level blog posts regarding programming, and more specifically web development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oshawadesign.com" # the base hostname & protocol for your site
twitter_username: realmunsterberg
github_username:  munsterberg

# Build settings
markdown: kramdown
